# https://www.safaribooksonline.com/library/view/docker-compose-in/100000006A0437/000206.html
version: '2'

services:

  wordpress:
    image: wordpress:4.5
    depends_on:
      - mysql
    restart: always # restart dependent on mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mysql:5.7
    restart: always # restart when database went down
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./volumes/db:/var/lib/mysql"
