/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'whan' at '3/19/16 10:29 AM' with Gradle 2.12
 *
 * @author whan, @date 3/19/16 10:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
