/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'whan' at '3/19/16 6:49 PM' with Gradle 2.12
 *
 * @author whan, @date 3/19/16 6:49 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
